### ISSUE TITLE
False positive type warnings for arbitrary argument PEP 484 if plugin used

### ISSUE THREAD

**Issue by andrianovs** [theY4Kman/pycharm-pytest-imp#11]
If pytest imp plugin used in PyCharm 2021.3.2 checking type of arbitrary argument (*args) is incorrect.

Steps to Reproduce
Create python file with code
```
def func1(*args):
    print(args[0])
    for arg in args:
        print(arg)

def func2(*args: int):
    print(args[0])
    for arg in args:
        print(arg)
```

If plugin disabled there are no inspection warnings in it.
If plugin enabled
function func2 has two warnings:
`Class 'int' does not define '__getitem__', so the '[]' operator cannot be used on its instances` for line `print(args[0])`
![изображение](https://user-images.githubusercontent.com/5956203/154519720-6e251d29-b4d5-4c16-8d0c-8fd901c5b3c1.png)
`Expected type 'collections.Iterable', got 'int' instead` for line `for arg in args:`
![изображение](https://user-images.githubusercontent.com/5956203/154519748-6cb70b5c-202e-44c5-9fd0-988c9e81469c.png)
But type of args displayed correctly as "tuple[int, ...] in same hint.

Bug in PyCharm issue tracker:
https://youtrack.jetbrains.com/issue/PY-53093

PyCharm 2021.3.2 (Community Edition)
Build #PC-213.6777.50, built on January 27, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (213.5744.190)
    ru.meanmail.plugin.requirements (2022.3-2021.3)
    com.y4kstudios.pytestimp (0.5.4)

**Comment by theY4Kman** [comment]
Sorry about this, and good catch, @lancelote. Honestly... embarrassingly... this has bitten me so much, and I thought PyCharm was just being stupid. Nope. My fault.

This was due to a _fix_ for #2, where explicitly declared type annotations on fixture declarations in test methods were being ignored. To fix it, I changed the type contributor to return the declared type of the argument, using `param.getArgumentType()`. This works for any argument... except `*args`. If `*args: int` is declared, `param.getArgumentType()` is `int`, _not_ `tuple[int]` — that magic appears to be included depending on the value of `param.isPositionalContainer`, which I was not checking.

But really, the behaviour the plugin should've had from the beginning is to return `null` if there's an explicit type declared, which instructs PyCharm to ignore the plugin's type contribution, and move on along the line (likely to PyCharm's own type contributor). That's the fix to the fix I pushed in version 0.5.5.

You can grab the plugin .zip directly from [the GH release](https://github.com/theY4Kman/pycharm-pytest-imp/releases/tag/0.5.5), or wait a day or two for Jetbrains to approve the plugin update, so you can update from the repository.

Thanks for reporting this; you've definitely made my life better :P And sorry for the trouble.
