### ISSUE TITLE
Python file with relative import breaks running a test from gutter run icon

### ISSUE THREAD

**Issue by scorpp** [theY4Kman/pycharm-pytest-imp#4]
Hi,

I know I have a vague issue, but still maybe you'll be able to track that down, or maybe someone would add their info.

Sometimes when file with test contains relative imports and I try to run a class\method test using gutter icon the plugin creates run configuration with wrong module path. Like test class is in `package.sub1.sub2.sub3` and run configuration run module `sub1.sub2.sub3.TestClass`.

I was unable to put together a clean project reproducing the issue. And I can't share my original code either.

Plugin version: 0.3.2
PyCharm version: PyCharm 2020.3 (Professional Edition) Build #PY-203.5981.165, built on December 15, 2020

**Comment by theY4Kman** [comment]
Interesting! In lieu of a working example, can you show me a scrubbed version of the ailing module's path, its offending relative import, and the path that pytest imp sets in the Run config? (Like, change the names, but keep them consistent)

**Comment by scorpp** [comment]
pycharm project root is
`/home/user/work/vendor/client/project-name/`
failing test is under 
`/home/user/work/vendor/client/project-name/project/screening/tests/views/api/sites/views/notes_tests.py`

When running the test class, run configuration has Target: module name
when failing target is
`screening.tests.views.api.sites.views.notes_tests.NotesApiViewTestCase`
when working it is
`notes_tests.NotesApiViewTestCase`

Offending import is
`from ......views.api.sites import NotesApiView`
When written as absolute it is
`from project.screening.views.api.sites import NotesApiView`

pytest.ini
```
[pytest]
; Arguments which used to run pytest.
addopts = -v -p no:warnings --reuse-db --ds=project.settings_test

; Tests lookup folder.
testpaths = project/tests
            project/common/tests
            project/portal/tests
            project/screening/tests
; Test Case class name pattern.
python_classes = *TestCase

python_files = *TestCase.py *_tests.py
```

**Comment by theY4Kman** [comment]
Thanks for the info! Lemme see if I can't repro

Also, ever since the last PyCharm release, I've noticed an issue where imports resolve to their containing file (https://youtrack.jetbrains.com/issue/PY-45797). I wonder if it's related. IDEA got a new EAP with the fix yesterday; PyCharm should follow shortly. Maybe I can test that hypothesis soon

**Comment by scorpp** [comment]
hey,

yesterday I updated pycharm to 2020.3.1 and seems like the issue is resolved now!

thanks for the tip! i think we can close the issue

**Comment by theY4Kman** [comment]
Oh, excellent! That's great, 'cause I dug in one late night and gave up after a few hours :P 

Well, I'll close it for now; feel free to reopen it if things don't work out (or comment, and I'll reopen it).

Thanks for the report, though, I appreciate the opportunity to improve the plugin... Even if it turned out to not be my backyard

**Comment by scorpp** [comment]
thank you!
