### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by radeklat** [theY4Kman/pycharm-pytest-imp#5]
`pytest` support configuration from `pyproject.toml` file instead of `pytest.ini` file [since version 6.0](https://docs.pytest.org/en/stable/customize.html#pyproject-toml). Would you please consider adding support for this file format?

Many tools around Python now allow using `pyproject.toml` because there is then just one configuration file in the repository. So I think this trend will only continue and it will be more common in the future. Thank you.

**Comment by theY4Kman** [comment]
That's a great idea! I just added support for reading the `tools.pytest.ini_options` of a `pyproject.toml` file. Just configure the path to the `pyproject.toml` in the settings, and you're good to go :)

![image](https://user-images.githubusercontent.com/33840/108305578-486c3f80-7178-11eb-8e0d-4a12c1178ec0.png)

I published it to the marketplace as version 0.4. It should be available in a day or two, pending JetBrains approval.

Thanks again for the suggestion!

**Comment by theY4Kman** [comment]
Holy crap, they approved it in record time – only 3 hours after submitting it! It should now be available within the Plugins section.

Oh, also, I forgot to mention: in the new build, I added support for the 2021.1 EAP

**Comment by umutseven92** [comment]
@theY4Kman Thank you for the quick response, this is awesome!

**Comment by radeklat** [comment]
@theY4Kman amazing! Thank you for implementing is so quickly :heart:

**Comment by radeklat** [comment]
@theY4Kman, @umutseven92 and I both tried the new feature and it doesn't recognize test function names when we use the `pyproject.toml` file. The file contains:

```toml
[tool.pytest.ini_options]
testpaths = "tests/unit tests/integration"
python_functions = "should_*"
```

but test functions starting with `should_` are no longer runnable. It does work with the `pytest.ini` file though.

**Comment by theY4Kman** [comment]
Oof, you're quite right; that's embarrassing. The functionality worked perfectly during testing, when launching the plugin from gradle... but it definitely does _not_ work when used from the stable channel :(

![pycharm-imp-works-in-ide](https://user-images.githubusercontent.com/33840/109402480-4ba7be00-7924-11eb-8e1a-c5ca878dbf19.gif)

![pycharm-imp-no-worky-from-stable-channel](https://user-images.githubusercontent.com/33840/109402482-4ea2ae80-7924-11eb-8c5b-5a85dba493bb.gif)

Honestly, I had no idea one could put pytest config into `pyproject.toml` until y'all opened this ticket. Since I use poetry for all my personal projects (which uses `pyproject.toml`), I'd love to kill an extra config file. So I want this feature just as well :P Lemme figure out what the hell is going on.

**Comment by theY4Kman** [comment]
Oh my god, I'm an idiot. Of course it doesn't work. I typoed the name of the `pyproject.toml` section: https://github.com/theY4Kman/pycharm-pytest-imp/blob/3a8159ab3fd8919f8a21b0a643d9ae354d09eb64/src/main/java/com/y4kstudios/pytestimp/PyTestImpService.kt#L164

I wrote
```
tools.pytest.ini_options
```

Instead of the correct
```
tool.pytest.ini_options
```

Oy gevalt.

**Comment by theY4Kman** [comment]
Man, double embarrassing.

![image](https://user-images.githubusercontent.com/33840/109405074-a51ae780-793a-11eb-86ac-d084b0fc7e65.png)

I'll push out a fix in 0.4.1 here shortly

**Comment by theY4Kman** [comment]
Okay, it's been submitted
![image](https://user-images.githubusercontent.com/33840/109405226-3b9bd880-793c-11eb-8826-f1a2d55a7971.png)

**Comment by umutseven92** [comment]
@theY4Kman Awesome, thank you for the quick response- can't wait!

**Comment by theY4Kman** [comment]
Yes, my quick response of 9 days ;)

FYI: I published the plugin .zip to the [0.4.1 GitHub Release](https://github.com/theY4Kman/pycharm-pytest-imp/releases/tag/0.4.1), which you can download and install manually to the IDE, if you wish to try it out sooner: https://github.com/theY4Kman/pycharm-pytest-imp/releases/download/0.4.1/pytest.imp-0.4.1.zip

**Comment by umutseven92** [comment]
In open source world, that is lightning fast :)

**Comment by radeklat** [comment]
@theY4Kman Thanks for the fix. I agree with @umutseven92, I also consider it very fast :D I just checked and it work correctly now :) Typos happen. If I had to count the number of times I was even looking at a diff and could not spot it :roll_eyes:
